site_name: "Mathesis"
site_description: Python library for formal logic (mathematical logic, philosophical logic), formal semantics, and theorem proving
# strict: true
site_url: https://digitalformallogic.github.io/mathesis/

theme:
  name: "material"
  language: en
  custom_dir: "docs/overrides"
  # font:
  #   text: Inter
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"
  features:
    - navigation.footer
    - navigation.expand
    - content.code.copy
  #   - content.tabs.link
  #   - content.code.annotate
  #   - announce.dismiss
  #   - navigation.tabs
  icon:
    logo: simple/matrix
    repo: fontawesome/brands/github
  # favicon: "favicon.png"

repo_name: digitalformallogic/mathesis
repo_url: https://github.com/digitalformallogic/mathesis
edit_uri: edit/master/docs/
# extra:
#   version:
#     provider: mike

# extra_css:
#   - "extra/terminal.css"
#   - "extra/tweaks.css"

extra_javascript:
  - js/extra.js
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#   - "extra/fluff.js"

nav:
  - Welcome to Mathesis: index.md
  - Get Started:
      - Installation: install.md
      - Use with JupyterLab/Jupyer Notebook: jupyter.py
      # - "Propositional logics": propositional.md
      # - "Predicate logics": predicate.md
  - Usage:
      - Formulas and Grammars: usage/grammars.md
      - Truth Tables: usage/truth-tables.py
      - Set-theoretic Models: usage/models.py
      - 🚧 Possible-world (Kripke) Semantics: usage/kripke.md
      - Proof in Tableau: usage/tableaux.md
      - Proof in Natural Deduction: usage/natural-deduction.md
      - Proof in Sequent Calculus: usage/sequent-calculi.md
      - Automated Reasoning: usage/automated-reasoning.md
  - Contributing: contributing.md
  - Alternatives: alternatives.md
  # - 🚧 API Reference:
  #     - "grammars": reference/grammars/index.md
  #     - "semantics.truth_table":
  #         - base: reference/semantics/base.md
  #         - classical: reference/semantics/classical.md
  #     - "semantics.model": reference/model.md

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  #   - admonition
  # - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: false
  - pymdownx.arithmatex:
      generic: true
  #   - pymdownx.details
  #   - pymdownx.superfences
  #   - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
        #   - pymdownx.tabbed:
        #       alternate_style: true


  - pymdownx.superfences:
      custom_fences:
        - name: python
          class: python
          validator: !!python/name:markdown_exec.validator
          format: !!python/name:markdown_exec.formatter

watch:
  - mathesis

plugins:
  # - mike:
  #     alias_type: symlink
  #     canonical_version: latest
  - search
  - markdown-exec
  - mkdocs-jupyter:
      execute: true
      ignore_h1_titles: true
  - exclude:
      glob:
        - plugins/*
        - __pycache__/*
  - mkdocstrings:
      handlers:
        python:
          options:
            # extensions:
            #   - griffe_typingdoc
            show_root_heading: true
            # show_if_no_docstring: true
            show_source: false
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters: ["!^_"]
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_symbol_type_heading: true # insiders
            show_symbol_type_toc: true # insiders
            show_submodules: true
  # - mkdocstrings:
  #     handlers:
  #       python:
  #         paths: [.]
  #         options:
  #           extensions:
  #             - griffe_typingdoc
  #           show_root_heading: true
  #           show_if_no_docstring: true
  #           members_order: source
  #           separate_signature: true
  #           filters: ["!^_"]
  #           docstring_options:
  #             ignore_init_summary: true
  #           merge_init_into_class: true
  #           # inherited_members: true
  #           show_submodules: true
  #           docstring_section_style: spacy
  #           signature_crossrefs: true
  #           show_symbol_type_heading: true
  #           show_symbol_type_toc: true
  #           # extensions:
  #           #   - docs/plugins/griffe_doclinks.py
  # - mkdocs-simple-hooks:
  #     hooks:
  #       on_pre_build: "docs.plugins.main:on_pre_build"
  #       on_files: "docs.plugins.main:on_files"
  #       on_page_markdown: "docs.plugins.main:on_page_markdown"
  # - redirects:
  #     redirect_maps:
  # - external-markdown:
